# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
# What is the value of the first triangle number to have over five hundred divisors?


def first_triangular_num():
    pass


if __name__ == "__main__":
    first_triangular_num()
